### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by Team319** [wpilibsuite/VisionBuildSamples#6]
Can't seem to get vision build samples to run. I am new to linux so probably something on my end. Any help?
![screenshot](https://user-images.githubusercontent.com/10764119/28972089-e0a633fc-791d-11e7-8d6d-912b90e7293c.png)

**Comment by AustinShalit** [comment]
It looks like the file is using CRLF line terminators.

**Comment by PeterJohnson** [comment]
You can run `dos2unix gradlew` to convert the file to unix line endings.

**Comment by PeterJohnson** [comment]
You may also need to make gradlew executable with `chmod a+x gradlew`

**Comment by Team319** [comment]
Build successful , used `dos2unix` did not need to `chmod a+x gradlew`

Thank you

**Comment by PeterJohnson** [comment]
Thanks for letting us know that worked.  Should be fixed for others via #7.
